name: my build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LUA: 51

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install dependencies
      run: |
        pip install pyserial
        sudo apt update
        sudo apt install -y srecord gcc-mingw-w64-x86-64

    - name: Build firmware
      run: |
        make clean
        make

    - name: Build luac.cross for Windows
      run: |
        # Очищаем временные объекты в подпапке кросс-компилятора
        make -C app/lua/luac_cross clean
        
        # Собираем exe с помощью MinGW, передавая его как основной компилятор
        make -C app/lua/luac_cross CC=x86_64-w64-mingw32-gcc
        
        # Переименовываем и переносим готовый файл в целевую директорию bin
        mv app/lua/luac_cross/luac.cross.exe bin/luac.cross_3.0.0-release_20240225_x64_float_Lua51.exe

    - name: Upload firmware and luac
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: firmware_and_luac.cross
        path: bin
