name: Build luac.cross

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Version tag'
        required: true
        default: '3.0.0.0-releas'

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build luac.cross.exe
      run: |
        msbuild msvc\hosttools.sln /m /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v143 /p:WindowsTargetPlatformVersion=10.0 /p:BuildInParallel=true
        copy msvc\luac-cross\x64\Release\luac.cross_${{ github.event.inputs.tag_name }}_x64_float_Lua51.exe luac.cross_${{ github.event.inputs.tag_name }}_x64_float_Lua51.exe
      shell: cmd

    - name: Upload luac.cross
      uses: actions/upload-artifact@v4
      with:
        name: luac.cross_${{ github.event.inputs.tag_name }}_x64_float_Lua51
        path: luac.cross_${{ github.event.inputs.tag_name }}_x64_float_Lua51.exe
