name: my build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LUA: 51

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        
    - run: pip install pyserial
    
    - run: sudo apt install srecord
    
    - name: Build firmware
      run: |
        make clean
        make
        
    - name: Upload firmware
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: firmware_51_float
        path: bin
