jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      # ... сборка ...
      - uses: actions/upload-artifact@v4
        with:
          name: luac.cross-win-x64
          path: luac.cross.exe
  
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        run: |
          cd src
          make luac.cross
      - uses: actions/upload-artifact@v4
        with:
          name: luac.cross-linux-x64
          path: src/luac.cross
