name: Build Documentation

on:
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install MkDocs Material
      run: |
        pip install mkdocs mkdocs-material

    - name: Build Docs Site
      run: |
        mkdocs build

    - name: Upload Docs Artifact
      uses: actions/upload-artifact@v4
      with:
        name: nodemcu-docs-html
        path: site/
