name: Build Windows Luac.Cross

on:
  workflow_dispatch:

jobs:
  build-luac:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build luac.cross for Windows
      run: |
        msbuild msvc/luac-cross/luac-cross.vcxproj /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v143

    - name: Rename and Prepare Artifact
      shell: bash
      run: |
        mkdir -p bin
        # Проверяем стандартное поведение MSBuild (исправленный путь без дублирования luac-cross)
        if [ -f "msvc/x64/Release/luac-cross.exe" ]; then
          cp msvc/x64/Release/luac-cross.exe bin/luac.cross_3.0.0-release_20240225_x64_float_Lua51.exe
        elif [ -f "msvc/luac-cross/x64/Release/luac-cross.exe" ]; then
          cp msvc/luac-cross/x64/Release/luac-cross.exe bin/luac.cross_3.0.0-release_20240225_x64_float_Lua51.exe
        else
          echo "Error: luac-cross.exe not found!" && exit 1
        fi

    - name: Upload Windows Executable
      uses: actions/upload-artifact@v4
      with:
        name: luac_windows_x64
        path: bin/
