name: Build luac.cross

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Build with official Docker image
        run: |
          docker run --rm \
            -v $(pwd):/opt/nodemcu-firmware \
            -w /opt/nodemcu-firmware \
            marcelstoer/nodemcu-build \
            /bin/bash -c "make -C tools luac.cross"
