name: Build luac.cross

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout NodeMCU firmware
        uses: actions/checkout@v4
        with:
          repository: nodemcu/nodemcu-firmware
          path: nodemcu-firmware

      - name: Build with official script
        working-directory: nodemcu-firmware
        run: |
          chmod +x tools/build.sh
          ./tools/build.sh -c luac.cross
